# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from geral import Ui_FormGeral


### Imports sistema ###
import mysql.connector
import pandas as pd

import tkinter
from tkinter import messagebox

### Arquivo variáveis de controle ###
import variaveisControle

### Variáveis de conexão com o banco de dados ###
host = variaveisControle.host
user = variaveisControle.user
password = variaveisControle.password
database = variaveisControle.database


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(479, 528)
                MainWindow.setStyleSheet("background-color: rgb(129, 181, 200);")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.txt_senha = QtWidgets.QLineEdit(self.centralwidget)
                self.txt_senha.setGeometry(QtCore.QRect(100, 297, 351, 31))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.txt_senha.setFont(font)
                self.txt_senha.setStyleSheet("border-radius: 15px;\n"
        "background-color: rgb(255, 255, 255);\n"
        "border-style: outset;\n"
        "border-color: black;\n"
        "border-width: 1px")
                self.txt_senha.setText("")
                self.txt_senha.setEchoMode(QtWidgets.QLineEdit.Password)
                self.txt_senha.setObjectName("txt_senha")
                self.lb_email = QtWidgets.QLabel(self.centralwidget)
                self.lb_email.setGeometry(QtCore.QRect(30, 200, 59, 41))
                font = QtGui.QFont()
                font.setPointSize(12)
                self.lb_email.setFont(font)
                self.lb_email.setObjectName("lb_email")
                self.txt_email = QtWidgets.QLineEdit(self.centralwidget)
                self.txt_email.setGeometry(QtCore.QRect(100, 207, 351, 31))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.txt_email.setFont(font)
                self.txt_email.setStyleSheet("border-radius: 15px;\n"
        "background-color: rgb(255, 255, 255);\n"
        "border-style: outset;\n"
        "border-color: black;\n"
        "border-width: 1px")
                self.txt_email.setText("")
                self.txt_email.setObjectName("txt_email")
                self.lb_senha = QtWidgets.QLabel(self.centralwidget)
                self.lb_senha.setGeometry(QtCore.QRect(20, 290, 71, 41))
                font = QtGui.QFont()
                font.setPointSize(12)
                self.lb_senha.setFont(font)
                self.lb_senha.setObjectName("lb_senha")
                self.bt_login = QtWidgets.QPushButton(self.centralwidget)
                self.bt_login.setGeometry(QtCore.QRect(170, 380, 141, 61))
                font = QtGui.QFont()
                font.setPointSize(18)
                self.bt_login.setFont(font)
                self.bt_login.setStyleSheet("background-color: rgb(85, 170, 127);\n"
        "")
                self.bt_login.setObjectName("bt_login")
                self.lb_login_icon = QtWidgets.QLabel(self.centralwidget)
                self.lb_login_icon.setGeometry(QtCore.QRect(140, 20, 211, 171))
                self.lb_login_icon.setStyleSheet("image: url(:/login_icon/imagens/login.png)")
                self.lb_login_icon.setText("")
                self.lb_login_icon.setObjectName("lb_login_icon")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 479, 26))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
                self.lb_email.setText(_translate("MainWindow", "Email:"))
                self.lb_senha.setText(_translate("MainWindow", "Senha:"))
                self.bt_login.setText(_translate("MainWindow", "Login"))
                self.lb_login_icon.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/login_icon/imagens/login.png\"/></p></body></html>"))

##################################################################################################
######################################### BOTÕES SISTEMA #########################################
##################################################################################################

                self.bt_login.clicked.connect(self.login)

###################################################################################################
######################################### FUNÇÕES SISTEMA #########################################
###################################################################################################

        def login(self):
                email = self.txt_email.text()
                senha = self.txt_senha.text()
                mydb = mysql.connector.connect(
                        host = host,
                        user = user,
                        password = password,
                        database = database
                        )
                root = tkinter.Tk()
                root.withdraw()

                try:
                        mycursor = mydb.cursor()
                        consultaSQL = "SELECT senha FROM usuario WHERE email = '{}'".format(email)
                        mycursor.execute(consultaSQL)
                        myresult = mycursor.fetchall()
                        mycursor.close()
                        
                        if senha == myresult[0][0]:
                                self.FormGeral = QtWidgets.QWidget()
                                self.ui = Ui_FormGeral()
                                self.ui.setupUi(self.FormGeral)
                                self.FormGeral.show()     
                        else:
                                messagebox.showerror("Erro ao fazer LOGIN", "USUÁRIO NÃO CADASTRADO")
                
                except:
                        messagebox.showerror("Erro ao fazer LOGIN", "USUÁIO NÃO CADASTRADO")
                self.txt_email.setText("")
                self.txt_senha.setText("")

import login_icon


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
